info: {}
name: ring_double_gdsfactoryp_f1bf23bf
settings:
  bend: bend_euler
  coupler_ring: coupler_ring
  cross_section: strip
  gap: 0.2
  length_extension: 3
  length_x: 0.01
  length_y: 0.01
  radius: 10
  straight: straight
